language: node_js
node_js:
  - lts/*


cache:
  directories:
    - ~/.npm
    - ~/.cache


jobs:
  include:
    - stage: build
      script:
        - npm ci
        - npm run build
      workspaces:
        use: build1
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: $AWS_S3
        skip_cleanup: true
        local_dir: public
        upload-dir: $AWS_S3_DIR
        on:
          branch: travis

